export const API_KEY = "3b55d67f9619a0d62ea9fa318f76663c";
export const img_Path = "https://image.tmdb.org/t/p/original";
export const poster_Path = "https://image.tmdb.org/t/p/w342";
export const Trending = "/trending/all/week";
export const Trending_Movies ="/trending/movie/week";
export const Trending_Shows ="/trending/tv/week";
export const Movies = "/movie/now_playing";
export const Tv = "/tv/on_the_air";
export const Top_Movies="/movie/top_rated";
export const Top_Tv="/tv/top_rated";
export const Pop_Movies="/movie/popular";
export const Pop_Tv="/tv/popular";
export const Similar_Movies = "/movie/{movie_id}/similar"
export const Similar_Tv = "/tv/{series_id}/similar"
export const Movie_details = "/movie/{movie_id}"
export const Tv_details = "/tv/{series_id}"
